set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED TRUE)
set(CMAKE_CXX_EXTENSIONS FALSE)
set(CMAKE_CXX_VISIBILITY_PRESET hidden)
set(CMAKE_VISIBILITY_INLINES_HIDDEN TRUE)
set(CMAKE_WIN32_EXECUTABLE TRUE)
set(CMAKE_AUTOMOC TRUE)
set(CMAKE_INSTALL_PREFIX ${CMAKE_BINARY_DIR}/install)
set(CMAKE_DEBUG_POSTFIX d)

if (MSVC)
    add_compile_options(/W4 /permissive-)
else()
    add_compile_options(-Wall -Wextra -pedantic-errors)
    if (CMAKE_CXX_COMPILER_ID STREQUAL Clang) # NOT AppleClang
        add_link_options(-fuse-ld=lld)
    endif()
endif()

if (ANDROID)
    set(QT_PLATFORM android)
elseif (UNIX AND NOT APPLE)
    set(QT_PLATFORM linux)
elseif (UIKIT AND NOT WATCHOS)
    set(QT_PLATFORM ios)
elseif (MACOS)
    set(QT_PLATFORM macos)
elseif (WIN32)
    set(QT_PLATFORM windows)
else()
    message(FATAL_ERROR "Unable to deduce the target platform")
endif()

add_compile_definitions(QT_PLATFORM=${QT_PLATFORM})

include(GenerateExportHeader)
