name: Automated GitHub Releases

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: omergoktas/qt6bionic:qtbase

    steps:
    - uses: actions/checkout@v3

    - name: Install required packages
      shell: bash
      run: |
        apt-get update -y
        apt-get install -y patchelf

    - name: Configure the project
      run: cmake -S . -B ../build

    - name: Build the project
      run: cmake --build ../build --parallel

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "continuous"
        title: "latest"
        prerelease: false
        files: linuxdeployqt-continuous-x86_64.AppImage
