name: Automated Builds

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Download source codes
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y build-essential patchelf libfuse2

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.0'
        cache: 'true'
        install-deps: 'false'

    - name: Build the project
      run: |
        cmake -S . -B build
        cmake --build build --parallel --config Release

    - name: Publish build artifacts
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: latest
        title: latest
        prerelease: false
        files: build/deploy/*.AppImage
